################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
CC_SRCS := 
C_SRCS := 
CC_DEPS := 
SX_DEPS := 
C++_DEPS := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
SECONDARY_FLASH := 
SECONDARY_SIZE := 
ASM_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src \
src/lcd_setup \
src/lvgl/examples/anim \
src/lvgl/examples/assets \
src/lvgl/examples/event \
src/lvgl/examples/get_started \
src/lvgl/examples/layouts/flex \
src/lvgl/examples/layouts/grid \
src/lvgl/examples/others/snapshot \
src/lvgl/examples/porting \
src/lvgl/examples/scroll \
src/lvgl/examples/styles \
src/lvgl/examples/widgets/animimg \
src/lvgl/examples/widgets/arc \
src/lvgl/examples/widgets/bar \
src/lvgl/examples/widgets/btn \
src/lvgl/examples/widgets/btnmatrix \
src/lvgl/examples/widgets/calendar \
src/lvgl/examples/widgets/canvas \
src/lvgl/examples/widgets/chart \
src/lvgl/examples/widgets/checkbox \
src/lvgl/examples/widgets/colorwheel \
src/lvgl/examples/widgets/dropdown \
src/lvgl/examples/widgets/img \
src/lvgl/examples/widgets/imgbtn \
src/lvgl/examples/widgets/keyboard \
src/lvgl/examples/widgets/label \
src/lvgl/examples/widgets/led \
src/lvgl/examples/widgets/line \
src/lvgl/examples/widgets/list \
src/lvgl/examples/widgets/meter \
src/lvgl/examples/widgets/msgbox \
src/lvgl/examples/widgets/obj \
src/lvgl/examples/widgets/roller \
src/lvgl/examples/widgets/slider \
src/lvgl/examples/widgets/span \
src/lvgl/examples/widgets/spinbox \
src/lvgl/examples/widgets/spinner \
src/lvgl/examples/widgets/switch \
src/lvgl/examples/widgets/table \
src/lvgl/examples/widgets/tabview \
src/lvgl/examples/widgets/textarea \
src/lvgl/examples/widgets/tileview \
src/lvgl/examples/widgets/win \
src/lvgl/src/core \
src/lvgl/src/draw \
src/lvgl/src/extra/layouts/flex \
src/lvgl/src/extra/layouts/grid \
src/lvgl/src/extra \
src/lvgl/src/extra/others/snapshot \
src/lvgl/src/extra/themes/basic \
src/lvgl/src/extra/themes/default \
src/lvgl/src/extra/themes/mono \
src/lvgl/src/extra/widgets/animimg \
src/lvgl/src/extra/widgets/calendar \
src/lvgl/src/extra/widgets/chart \
src/lvgl/src/extra/widgets/colorwheel \
src/lvgl/src/extra/widgets/imgbtn \
src/lvgl/src/extra/widgets/keyboard \
src/lvgl/src/extra/widgets/led \
src/lvgl/src/extra/widgets/list \
src/lvgl/src/extra/widgets/meter \
src/lvgl/src/extra/widgets/msgbox \
src/lvgl/src/extra/widgets/span \
src/lvgl/src/extra/widgets/spinbox \
src/lvgl/src/extra/widgets/spinner \
src/lvgl/src/extra/widgets/tabview \
src/lvgl/src/extra/widgets/tileview \
src/lvgl/src/extra/widgets/win \
src/lvgl/src/font \
src/lvgl/src/gpu \
src/lvgl/src/hal \
src/lvgl/src/misc \
src/lvgl/src/widgets \
src/lvgl/tests/src \
src/lvgl/tests/src/test_cases \
src/lvgl/tests/src/test_fonts \
src/lvgl/tests/unity \
src/synergy_gen \
synergy/board/s5d9_pk \
synergy/ssp/src/bsp/cmsis/Device/RENESAS/S5D9/Source \
synergy/ssp/src/bsp/mcu/all \
synergy/ssp/src/bsp/mcu/s5d9 \
synergy/ssp/src/driver/r_cgc \
synergy/ssp/src/driver/r_dtc \
synergy/ssp/src/driver/r_elc \
synergy/ssp/src/driver/r_fmi \
synergy/ssp/src/driver/r_glcd \
synergy/ssp/src/driver/r_icu \
synergy/ssp/src/driver/r_ioport \
synergy/ssp/src/driver/r_jpeg_common \
synergy/ssp/src/driver/r_jpeg_decode \
synergy/ssp/src/driver/r_riic \
synergy/ssp/src/driver/r_sci_spi \
synergy/ssp/src/framework/sf_el_gx \
synergy/ssp/src/framework/sf_external_irq \
synergy/ssp/src/framework/sf_jpeg_decode \
synergy/ssp/src/framework/sf_message \
synergy/ssp/src/framework/sf_tes_2d_drw \
synergy/ssp/src/framework/sf_touch_panel_i2c \
synergy/ssp/src/framework/tes/dave2d \
synergy/ssp_supplemental/touch_drivers/touch_panel_i2c_sx8654 \

